<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OtSeeder extends Seeder
{
    public function run(): void
    {
        $hospitalId = 1;

        // Get existing doctors for assignments
        $doctors = DB::table('doctors')->where('hospital_id', $hospitalId)->get();
        $surgeonIds = $doctors->pluck('doctor_id')->toArray();

        // Create Operation Theaters
        $theaters = [
            [
                'hospital_id' => $hospitalId,
                'ot_code' => 'OT01',
                'ot_name' => 'Operation Theater 1 - Major',
                'ot_type' => 'major',
                'floor' => '2nd Floor',
                'capacity' => 1,
                'has_laminar_flow' => true,
                'has_c_arm' => true,
                'has_laparoscopy' => true,
                'charges_per_hour' => 5000.00,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'ot_code' => 'OT02',
                'ot_name' => 'Operation Theater 2 - Major',
                'ot_type' => 'major',
                'floor' => '2nd Floor',
                'capacity' => 1,
                'has_laminar_flow' => true,
                'has_c_arm' => false,
                'has_laparoscopy' => true,
                'charges_per_hour' => 4500.00,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'ot_code' => 'OT03',
                'ot_name' => 'Minor OT',
                'ot_type' => 'minor',
                'floor' => '1st Floor',
                'capacity' => 1,
                'has_laminar_flow' => false,
                'has_c_arm' => false,
                'has_laparoscopy' => false,
                'charges_per_hour' => 2000.00,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'ot_code' => 'OT04',
                'ot_name' => 'Day Care OT',
                'ot_type' => 'daycare',
                'floor' => '1st Floor',
                'capacity' => 2,
                'has_laminar_flow' => false,
                'has_c_arm' => false,
                'has_laparoscopy' => false,
                'charges_per_hour' => 1500.00,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'ot_code' => 'EMOT',
                'ot_name' => 'Emergency OT',
                'ot_type' => 'emergency',
                'floor' => 'Ground Floor',
                'capacity' => 1,
                'has_laminar_flow' => true,
                'has_c_arm' => true,
                'has_laparoscopy' => false,
                'charges_per_hour' => 6000.00,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('operation_theaters')->insert($theaters);

        // Create Surgery Types
        $surgeryTypes = [
            // General Surgery
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'SURG001',
                'surgery_name' => 'Appendectomy',
                'department_id' => 1,
                'specialty' => 'General Surgery',
                'category' => 'elective',
                'complexity' => 'moderate',
                'estimated_duration_mins' => 60,
                'base_charges' => 25000.00,
                'surgeon_fee' => 8000.00,
                'anesthesia_type' => 'general',
                'requires_icu' => false,
                'requires_blood' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'SURG002',
                'surgery_name' => 'Laparoscopic Cholecystectomy',
                'department_id' => 1,
                'specialty' => 'General Surgery',
                'category' => 'elective',
                'complexity' => 'moderate',
                'estimated_duration_mins' => 90,
                'base_charges' => 45000.00,
                'surgeon_fee' => 15000.00,
                'anesthesia_type' => 'general',
                'requires_icu' => false,
                'requires_blood' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'SURG003',
                'surgery_name' => 'Hernia Repair',
                'department_id' => 1,
                'specialty' => 'General Surgery',
                'category' => 'elective',
                'complexity' => 'minor',
                'estimated_duration_mins' => 45,
                'base_charges' => 20000.00,
                'surgeon_fee' => 6000.00,
                'anesthesia_type' => 'regional',
                'requires_icu' => false,
                'requires_blood' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Orthopedic Surgery
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'ORTH001',
                'surgery_name' => 'Total Knee Replacement',
                'department_id' => 4,
                'specialty' => 'Orthopedics',
                'category' => 'elective',
                'complexity' => 'major',
                'estimated_duration_mins' => 120,
                'base_charges' => 150000.00,
                'surgeon_fee' => 50000.00,
                'anesthesia_type' => 'regional',
                'requires_icu' => true,
                'requires_blood' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'ORTH002',
                'surgery_name' => 'Total Hip Replacement',
                'department_id' => 4,
                'specialty' => 'Orthopedics',
                'category' => 'elective',
                'complexity' => 'major',
                'estimated_duration_mins' => 150,
                'base_charges' => 180000.00,
                'surgeon_fee' => 60000.00,
                'anesthesia_type' => 'general',
                'requires_icu' => true,
                'requires_blood' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'ORTH003',
                'surgery_name' => 'Fracture Fixation (ORIF)',
                'department_id' => 4,
                'specialty' => 'Orthopedics',
                'category' => 'emergency',
                'complexity' => 'moderate',
                'estimated_duration_mins' => 90,
                'base_charges' => 35000.00,
                'surgeon_fee' => 12000.00,
                'anesthesia_type' => 'regional',
                'requires_icu' => false,
                'requires_blood' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'ORTH004',
                'surgery_name' => 'Arthroscopy - Knee',
                'department_id' => 4,
                'specialty' => 'Orthopedics',
                'category' => 'day_care',
                'complexity' => 'minor',
                'estimated_duration_mins' => 45,
                'base_charges' => 25000.00,
                'surgeon_fee' => 10000.00,
                'anesthesia_type' => 'regional',
                'requires_icu' => false,
                'requires_blood' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Gynecology Surgery
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'GYN001',
                'surgery_name' => 'Cesarean Section',
                'department_id' => 6,
                'specialty' => 'Gynecology',
                'category' => 'emergency',
                'complexity' => 'moderate',
                'estimated_duration_mins' => 60,
                'base_charges' => 35000.00,
                'surgeon_fee' => 12000.00,
                'anesthesia_type' => 'regional',
                'requires_icu' => false,
                'requires_blood' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'GYN002',
                'surgery_name' => 'Hysterectomy (Abdominal)',
                'department_id' => 6,
                'specialty' => 'Gynecology',
                'category' => 'elective',
                'complexity' => 'major',
                'estimated_duration_mins' => 120,
                'base_charges' => 60000.00,
                'surgeon_fee' => 20000.00,
                'anesthesia_type' => 'general',
                'requires_icu' => false,
                'requires_blood' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'GYN003',
                'surgery_name' => 'Laparoscopic Hysterectomy',
                'department_id' => 6,
                'specialty' => 'Gynecology',
                'category' => 'elective',
                'complexity' => 'major',
                'estimated_duration_mins' => 150,
                'base_charges' => 80000.00,
                'surgeon_fee' => 30000.00,
                'anesthesia_type' => 'general',
                'requires_icu' => false,
                'requires_blood' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ENT Surgery
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'ENT001',
                'surgery_name' => 'Tonsillectomy',
                'department_id' => 8,
                'specialty' => 'ENT',
                'category' => 'elective',
                'complexity' => 'minor',
                'estimated_duration_mins' => 45,
                'base_charges' => 18000.00,
                'surgeon_fee' => 5000.00,
                'anesthesia_type' => 'general',
                'requires_icu' => false,
                'requires_blood' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'ENT002',
                'surgery_name' => 'Septoplasty',
                'department_id' => 8,
                'specialty' => 'ENT',
                'category' => 'elective',
                'complexity' => 'moderate',
                'estimated_duration_mins' => 90,
                'base_charges' => 30000.00,
                'surgeon_fee' => 10000.00,
                'anesthesia_type' => 'general',
                'requires_icu' => false,
                'requires_blood' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Ophthalmology
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'OPH001',
                'surgery_name' => 'Cataract Surgery (Phaco)',
                'department_id' => 9,
                'specialty' => 'Ophthalmology',
                'category' => 'day_care',
                'complexity' => 'minor',
                'estimated_duration_mins' => 30,
                'base_charges' => 25000.00,
                'surgeon_fee' => 8000.00,
                'anesthesia_type' => 'local',
                'requires_icu' => false,
                'requires_blood' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Cardiology/Cardiac Surgery
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'CARD001',
                'surgery_name' => 'Coronary Artery Bypass Graft (CABG)',
                'department_id' => 2,
                'specialty' => 'Cardiac Surgery',
                'category' => 'elective',
                'complexity' => 'super_specialty',
                'estimated_duration_mins' => 300,
                'base_charges' => 350000.00,
                'surgeon_fee' => 100000.00,
                'anesthesia_type' => 'general',
                'requires_icu' => true,
                'requires_blood' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'surgery_code' => 'CARD002',
                'surgery_name' => 'Angioplasty with Stent',
                'department_id' => 2,
                'specialty' => 'Interventional Cardiology',
                'category' => 'emergency',
                'complexity' => 'major',
                'estimated_duration_mins' => 90,
                'base_charges' => 150000.00,
                'surgeon_fee' => 40000.00,
                'anesthesia_type' => 'local',
                'requires_icu' => true,
                'requires_blood' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('surgery_types')->insert($surgeryTypes);

        $this->command->info('OT Seeder completed: Created ' . count($theaters) . ' theaters and ' . count($surgeryTypes) . ' surgery types.');
    }
}
