<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RadiologySeeder extends Seeder
{
    public function run(): void
    {
        $hospitalId = 1;

        // Create Radiology Modalities
        $modalities = [
            [
                'hospital_id' => $hospitalId,
                'modality_code' => 'XRAY',
                'modality_name' => 'X-Ray',
                'description' => 'Digital X-Ray imaging for bones, chest, and abdomen',
                'room_number' => 'R-101',
                'is_contrast_available' => false,
                'default_tat_hours' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_code' => 'USG',
                'modality_name' => 'Ultrasound',
                'description' => 'Sonography for abdomen, pelvis, obstetrics, and soft tissue imaging',
                'room_number' => 'R-102',
                'is_contrast_available' => false,
                'default_tat_hours' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_code' => 'CT',
                'modality_name' => 'CT Scan',
                'description' => 'Computed Tomography for detailed cross-sectional imaging',
                'room_number' => 'R-103',
                'is_contrast_available' => true,
                'default_tat_hours' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_code' => 'MRI',
                'modality_name' => 'MRI',
                'description' => 'Magnetic Resonance Imaging for soft tissue and neurological imaging',
                'room_number' => 'R-104',
                'is_contrast_available' => true,
                'default_tat_hours' => 24,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_code' => 'MAMMO',
                'modality_name' => 'Mammography',
                'description' => 'Digital mammography for breast imaging and screening',
                'room_number' => 'R-105',
                'is_contrast_available' => false,
                'default_tat_hours' => 24,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_code' => 'FLUORO',
                'modality_name' => 'Fluoroscopy',
                'description' => 'Real-time X-ray imaging for GI studies and procedures',
                'room_number' => 'R-106',
                'is_contrast_available' => true,
                'default_tat_hours' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_code' => 'DEXA',
                'modality_name' => 'DEXA Scan',
                'description' => 'Bone density measurement for osteoporosis screening',
                'room_number' => 'R-107',
                'is_contrast_available' => false,
                'default_tat_hours' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('radiology_modalities')->insert($modalities);

        // Get inserted modality IDs
        $modalityIds = DB::table('radiology_modalities')
            ->where('hospital_id', $hospitalId)
            ->pluck('modality_id', 'modality_code')
            ->toArray();

        // Create Radiology Tests
        $tests = [
            // X-Ray Tests
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['XRAY'],
                'test_code' => 'XR-CHEST-PA',
                'test_name' => 'X-Ray Chest PA View',
                'body_part' => 'Chest',
                'laterality' => 'na',
                'rate' => 300.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove all metallic objects from chest area',
                'consent_required' => false,
                'tat_hours' => 2,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['XRAY'],
                'test_code' => 'XR-CHEST-LAT',
                'test_name' => 'X-Ray Chest Lateral View',
                'body_part' => 'Chest',
                'laterality' => 'na',
                'rate' => 300.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove all metallic objects from chest area',
                'consent_required' => false,
                'tat_hours' => 2,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['XRAY'],
                'test_code' => 'XR-ABD',
                'test_name' => 'X-Ray Abdomen',
                'body_part' => 'Abdomen',
                'laterality' => 'na',
                'rate' => 350.00,
                'contrast_required' => false,
                'preparation_instructions' => null,
                'consent_required' => false,
                'tat_hours' => 2,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['XRAY'],
                'test_code' => 'XR-SPINE-C',
                'test_name' => 'X-Ray Cervical Spine',
                'body_part' => 'Spine',
                'laterality' => 'na',
                'rate' => 400.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove jewelry around neck',
                'consent_required' => false,
                'tat_hours' => 2,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['XRAY'],
                'test_code' => 'XR-SPINE-LS',
                'test_name' => 'X-Ray Lumbar Spine',
                'body_part' => 'Spine',
                'laterality' => 'na',
                'rate' => 450.00,
                'contrast_required' => false,
                'preparation_instructions' => null,
                'consent_required' => false,
                'tat_hours' => 2,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['XRAY'],
                'test_code' => 'XR-KNEE',
                'test_name' => 'X-Ray Knee',
                'body_part' => 'Knee',
                'laterality' => 'bilateral',
                'rate' => 350.00,
                'contrast_required' => false,
                'preparation_instructions' => null,
                'consent_required' => false,
                'tat_hours' => 2,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['XRAY'],
                'test_code' => 'XR-HAND',
                'test_name' => 'X-Ray Hand',
                'body_part' => 'Hand',
                'laterality' => 'bilateral',
                'rate' => 300.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove rings and jewelry',
                'consent_required' => false,
                'tat_hours' => 2,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['XRAY'],
                'test_code' => 'XR-SKULL',
                'test_name' => 'X-Ray Skull',
                'body_part' => 'Skull',
                'laterality' => 'na',
                'rate' => 400.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove earrings and hairpins',
                'consent_required' => false,
                'tat_hours' => 2,
                'is_active' => true,
            ],
            // Ultrasound Tests
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['USG'],
                'test_code' => 'USG-ABD',
                'test_name' => 'USG Whole Abdomen',
                'body_part' => 'Abdomen',
                'laterality' => 'na',
                'rate' => 800.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Fasting for 6 hours. Full bladder required.',
                'consent_required' => false,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['USG'],
                'test_code' => 'USG-PELVIS',
                'test_name' => 'USG Pelvis',
                'body_part' => 'Pelvis',
                'laterality' => 'na',
                'rate' => 600.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Full bladder required',
                'consent_required' => false,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['USG'],
                'test_code' => 'USG-OBS',
                'test_name' => 'USG Obstetric',
                'body_part' => 'Uterus',
                'laterality' => 'na',
                'rate' => 700.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Full bladder for first trimester',
                'consent_required' => false,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['USG'],
                'test_code' => 'USG-THYROID',
                'test_name' => 'USG Thyroid',
                'body_part' => 'Thyroid',
                'laterality' => 'na',
                'rate' => 500.00,
                'contrast_required' => false,
                'preparation_instructions' => 'No preparation required',
                'consent_required' => false,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['USG'],
                'test_code' => 'USG-BREAST',
                'test_name' => 'USG Breast Bilateral',
                'body_part' => 'Breast',
                'laterality' => 'bilateral',
                'rate' => 700.00,
                'contrast_required' => false,
                'preparation_instructions' => 'No preparation required',
                'consent_required' => false,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['USG'],
                'test_code' => 'USG-KUB',
                'test_name' => 'USG KUB (Kidney, Ureter, Bladder)',
                'body_part' => 'Urinary System',
                'laterality' => 'na',
                'rate' => 600.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Full bladder required',
                'consent_required' => false,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['USG'],
                'test_code' => 'USG-DOPPLER',
                'test_name' => 'USG Color Doppler (Lower Limb)',
                'body_part' => 'Lower Limb',
                'laterality' => 'bilateral',
                'rate' => 1200.00,
                'contrast_required' => false,
                'preparation_instructions' => 'No preparation required',
                'consent_required' => false,
                'tat_hours' => 6,
                'is_active' => true,
            ],
            // CT Scan Tests
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['CT'],
                'test_code' => 'CT-HEAD',
                'test_name' => 'CT Head Plain',
                'body_part' => 'Head',
                'laterality' => 'na',
                'rate' => 2500.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove jewelry, hairpins',
                'consent_required' => true,
                'tat_hours' => 6,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['CT'],
                'test_code' => 'CT-HEAD-C',
                'test_name' => 'CT Head with Contrast',
                'body_part' => 'Head',
                'laterality' => 'na',
                'rate' => 3500.00,
                'contrast_required' => true,
                'contrast_rate' => 1500.00,
                'preparation_instructions' => 'Fasting 4 hours. Check kidney function. Remove jewelry.',
                'consent_required' => true,
                'tat_hours' => 6,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['CT'],
                'test_code' => 'CT-CHEST',
                'test_name' => 'CT Chest (HRCT)',
                'body_part' => 'Chest',
                'laterality' => 'na',
                'rate' => 3000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove metallic objects',
                'consent_required' => true,
                'tat_hours' => 6,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['CT'],
                'test_code' => 'CT-ABD',
                'test_name' => 'CT Abdomen Plain',
                'body_part' => 'Abdomen',
                'laterality' => 'na',
                'rate' => 3500.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Fasting 4-6 hours',
                'consent_required' => true,
                'tat_hours' => 6,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['CT'],
                'test_code' => 'CT-ABD-C',
                'test_name' => 'CT Abdomen with Contrast',
                'body_part' => 'Abdomen',
                'laterality' => 'na',
                'rate' => 5000.00,
                'contrast_required' => true,
                'contrast_rate' => 1500.00,
                'preparation_instructions' => 'Fasting 6 hours. Check creatinine levels.',
                'consent_required' => true,
                'tat_hours' => 6,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['CT'],
                'test_code' => 'CT-KUB',
                'test_name' => 'CT KUB (Stone Protocol)',
                'body_part' => 'Urinary System',
                'laterality' => 'na',
                'rate' => 3000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Full bladder preferred',
                'consent_required' => true,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['CT'],
                'test_code' => 'CT-ANGIO',
                'test_name' => 'CT Angiography',
                'body_part' => 'Blood Vessels',
                'laterality' => 'na',
                'rate' => 8000.00,
                'contrast_required' => true,
                'contrast_rate' => 2000.00,
                'preparation_instructions' => 'Fasting 6 hours. Check kidney function. IV access required.',
                'consent_required' => true,
                'tat_hours' => 12,
                'is_active' => true,
            ],
            // MRI Tests
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['MRI'],
                'test_code' => 'MRI-BRAIN',
                'test_name' => 'MRI Brain Plain',
                'body_part' => 'Brain',
                'laterality' => 'na',
                'rate' => 6000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove all metallic objects. No pacemakers allowed.',
                'consent_required' => true,
                'tat_hours' => 24,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['MRI'],
                'test_code' => 'MRI-BRAIN-C',
                'test_name' => 'MRI Brain with Contrast',
                'body_part' => 'Brain',
                'laterality' => 'na',
                'rate' => 8000.00,
                'contrast_required' => true,
                'contrast_rate' => 2500.00,
                'preparation_instructions' => 'Remove all metallic objects. Check kidney function. No pacemakers.',
                'consent_required' => true,
                'tat_hours' => 24,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['MRI'],
                'test_code' => 'MRI-SPINE-C',
                'test_name' => 'MRI Cervical Spine',
                'body_part' => 'Cervical Spine',
                'laterality' => 'na',
                'rate' => 6000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove metallic objects. No pacemakers allowed.',
                'consent_required' => true,
                'tat_hours' => 24,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['MRI'],
                'test_code' => 'MRI-SPINE-LS',
                'test_name' => 'MRI Lumbar Spine',
                'body_part' => 'Lumbar Spine',
                'laterality' => 'na',
                'rate' => 6000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove metallic objects. No pacemakers allowed.',
                'consent_required' => true,
                'tat_hours' => 24,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['MRI'],
                'test_code' => 'MRI-KNEE',
                'test_name' => 'MRI Knee',
                'body_part' => 'Knee',
                'laterality' => 'bilateral',
                'rate' => 6000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Remove metallic objects from lower limb.',
                'consent_required' => true,
                'tat_hours' => 24,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['MRI'],
                'test_code' => 'MRI-ABD',
                'test_name' => 'MRI Abdomen',
                'body_part' => 'Abdomen',
                'laterality' => 'na',
                'rate' => 8000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Fasting 4-6 hours. Remove metallic objects.',
                'consent_required' => true,
                'tat_hours' => 24,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['MRI'],
                'test_code' => 'MRCP',
                'test_name' => 'MRCP (MR Cholangiopancreatography)',
                'body_part' => 'Biliary System',
                'laterality' => 'na',
                'rate' => 9000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'Fasting 6-8 hours. No metallic objects.',
                'consent_required' => true,
                'tat_hours' => 24,
                'is_active' => true,
            ],
            // Mammography Tests
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['MAMMO'],
                'test_code' => 'MAMMO-SCREEN',
                'test_name' => 'Digital Mammography (Screening)',
                'body_part' => 'Breast',
                'laterality' => 'bilateral',
                'rate' => 1500.00,
                'contrast_required' => false,
                'preparation_instructions' => 'No deodorant or powder on day of exam',
                'consent_required' => true,
                'tat_hours' => 24,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['MAMMO'],
                'test_code' => 'MAMMO-DIAG',
                'test_name' => 'Digital Mammography (Diagnostic)',
                'body_part' => 'Breast',
                'laterality' => 'bilateral',
                'rate' => 2000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'No deodorant or powder on day of exam',
                'consent_required' => true,
                'tat_hours' => 24,
                'is_active' => true,
            ],
            // DEXA Tests
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['DEXA'],
                'test_code' => 'DEXA-SPINE',
                'test_name' => 'DEXA Spine',
                'body_part' => 'Spine',
                'laterality' => 'na',
                'rate' => 1000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'No calcium supplements 24 hours prior',
                'consent_required' => false,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['DEXA'],
                'test_code' => 'DEXA-HIP',
                'test_name' => 'DEXA Hip',
                'body_part' => 'Hip',
                'laterality' => 'bilateral',
                'rate' => 1000.00,
                'contrast_required' => false,
                'preparation_instructions' => 'No calcium supplements 24 hours prior',
                'consent_required' => false,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['DEXA'],
                'test_code' => 'DEXA-WHOLE',
                'test_name' => 'DEXA Whole Body',
                'body_part' => 'Whole Body',
                'laterality' => 'na',
                'rate' => 1800.00,
                'contrast_required' => false,
                'preparation_instructions' => 'No calcium supplements 24 hours prior',
                'consent_required' => false,
                'tat_hours' => 4,
                'is_active' => true,
            ],
            // Fluoroscopy Tests
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['FLUORO'],
                'test_code' => 'BARIUM-SWALLOW',
                'test_name' => 'Barium Swallow',
                'body_part' => 'Esophagus',
                'laterality' => 'na',
                'rate' => 1500.00,
                'contrast_required' => true,
                'contrast_rate' => 500.00,
                'preparation_instructions' => 'NPO after midnight',
                'consent_required' => true,
                'tat_hours' => 6,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['FLUORO'],
                'test_code' => 'BARIUM-MEAL',
                'test_name' => 'Barium Meal',
                'body_part' => 'Stomach',
                'laterality' => 'na',
                'rate' => 1800.00,
                'contrast_required' => true,
                'contrast_rate' => 500.00,
                'preparation_instructions' => 'NPO after midnight',
                'consent_required' => true,
                'tat_hours' => 6,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['FLUORO'],
                'test_code' => 'BARIUM-ENEMA',
                'test_name' => 'Barium Enema',
                'body_part' => 'Colon',
                'laterality' => 'na',
                'rate' => 2000.00,
                'contrast_required' => true,
                'contrast_rate' => 500.00,
                'preparation_instructions' => 'Bowel preparation required. Clear liquids day before.',
                'consent_required' => true,
                'tat_hours' => 6,
                'is_active' => true,
            ],
            [
                'hospital_id' => $hospitalId,
                'modality_id' => $modalityIds['FLUORO'],
                'test_code' => 'IVU',
                'test_name' => 'Intravenous Urography (IVU)',
                'body_part' => 'Urinary System',
                'laterality' => 'na',
                'rate' => 2500.00,
                'contrast_required' => true,
                'contrast_rate' => 1000.00,
                'preparation_instructions' => 'Check kidney function. Bowel prep may be needed.',
                'consent_required' => true,
                'tat_hours' => 6,
                'is_active' => true,
            ],
        ];

        foreach ($tests as $test) {
            $test['created_at'] = now();
            $test['updated_at'] = now();
            if (!isset($test['contrast_rate'])) {
                $test['contrast_rate'] = 0;
            }
            DB::table('radiology_tests')->insert($test);
        }

        $this->command->info('Radiology Seeder completed: Created ' . count($modalities) . ' modalities and ' . count($tests) . ' tests.');
    }
}
